### ISSUE TITLE
Game running way too fast

### ISSUE THREAD

**Issue by iluuu1994** [Majki92/SwiftEmu#1]
Awesome project!

I noticed that Super Mario Land was running extremely slow so I built it with in Release Mode with whole module optimizations turned on. Now the exact opposite was happening, the game was running way too fast.

My best guess is that you're not limiting the update procedure to 60 (or whatever) calls per second.

**Comment by Majki92** [comment]
Yeah, that is not yet implemented, right now I have very little free time. I should probably add it to TODO list ;) Nevertheless this project is still in very early stage ;) I wish to finish it in the future. If you have a good idea how to do it efficiently in swift, please share ;) The simplest delay with sleep is not a good idea :(

**Comment by Majki92** [comment]
OK, this should now be fixed ;)
I would appreciate your feedback ;)

**Comment by Majki92** [comment]
Sorry for the force push. This issue system in github is quite new to me ;)
